# Generated by Django 6.0.3 on 2026-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
